baseURL: "https://xn--adrianlucrcecleste-0vbx.page"
title: Adrian's Blog
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10


params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: "Adrian Lucrèce Céleste"
  # author: ["Me", "You"] # multiple authors
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  # images: ""
  # assets:
  #   favicon: '<path / external url>'

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Adrian's Blog"
    Content: A blog about things

  socialIcons:
    - name: twitter
      url: "https://twitter.com/lucrececeleste"
    - name: github
      url: "https://github.com/adriankoshka"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
